version: '3.7'

services:
  rabbit:
    image: rabbitmq:${RABBITMQ_IMAGE_TAG:-3.12.2-management-alpine}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:?}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:?}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  rabbitmq:
    name: rabbitmq
    external: true

volumes:
  rabbitmq-data:
